//Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package types

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufExtraInfo = []byte{132}

func (t *ExtraInfo) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufExtraInfo); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.GraphSyncUrl (string) (string)
	if len(t.GraphSyncUrl) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.GraphSyncUrl was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.GraphSyncUrl))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.GraphSyncUrl)); err != nil {
		return err
	}

	// t.GoLegsSubUrl (string) (string)
	if len(t.GoLegsSubUrl) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.GoLegsSubUrl was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.GoLegsSubUrl))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.GoLegsSubUrl)); err != nil {
		return err
	}

	// t.GolegsSubTopic (string) (string)
	if len(t.GolegsSubTopic) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.GolegsSubTopic was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.GolegsSubTopic))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.GolegsSubTopic)); err != nil {
		return err
	}

	// t.MultiAddr (string) (string)
	if len(t.MultiAddr) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.MultiAddr was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.MultiAddr))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.MultiAddr)); err != nil {
		return err
	}
	return nil
}

func (t *ExtraInfo) UnmarshalCBOR(r io.Reader) error {
	*t = ExtraInfo{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 4 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.GraphSyncUrl (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.GraphSyncUrl = string(sval)
	}
	// t.GoLegsSubUrl (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.GoLegsSubUrl = string(sval)
	}
	// t.GolegsSubTopic (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.GolegsSubTopic = string(sval)
	}
	// t.MultiAddr (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.MultiAddr = string(sval)
	}
	return nil
}

var lengthBufSnapShot = []byte{133}

func (t *SnapShot) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufSnapShot); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.Update (map[string]*types.ProviderState) (map)
	{
		if len(t.Update) > 4096 {
			return xerrors.Errorf("cannot marshal t.Update map too large")
		}

		if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajMap, uint64(len(t.Update))); err != nil {
			return err
		}

		keys := make([]string, 0, len(t.Update))
		for k := range t.Update {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			v := t.Update[k]

			if len(k) > cbg.MaxLength {
				return xerrors.Errorf("Value in field k was too long")
			}

			if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(k))); err != nil {
				return err
			}
			if _, err := io.WriteString(w, string(k)); err != nil {
				return err
			}

			if err := v.MarshalCBOR(w); err != nil {
				return err
			}

		}
	}

	// t.Height (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Height)); err != nil {
		return err
	}

	// t.CreateTime (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.CreateTime)); err != nil {
		return err
	}

	// t.PrevSnapShot (string) (string)
	if len(t.PrevSnapShot) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.PrevSnapShot was too long")
	}

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.PrevSnapShot))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.PrevSnapShot)); err != nil {
		return err
	}

	// t.ExtraInfo (types.ExtraInfo) (struct)
	if err := t.ExtraInfo.MarshalCBOR(w); err != nil {
		return err
	}
	return nil
}

func (t *SnapShot) UnmarshalCBOR(r io.Reader) error {
	*t = SnapShot{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 5 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Update (map[string]*types.ProviderState) (map)

	maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajMap {
		return fmt.Errorf("expected a map (major type 5)")
	}
	if extra > 4096 {
		return fmt.Errorf("t.Update: map too large")
	}

	t.Update = make(map[string]*ProviderState, extra)

	for i, l := 0, int(extra); i < l; i++ {

		var k string

		{
			sval, err := cbg.ReadStringBuf(br, scratch)
			if err != nil {
				return err
			}

			k = string(sval)
		}

		var v *ProviderState

		{

			b, err := br.ReadByte()
			if err != nil {
				return err
			}
			if b != cbg.CborNull[0] {
				if err := br.UnreadByte(); err != nil {
					return err
				}
				v = new(ProviderState)
				if err := v.UnmarshalCBOR(br); err != nil {
					return xerrors.Errorf("unmarshaling v pointer: %w", err)
				}
			}

		}

		t.Update[k] = v

	}
	// t.Height (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Height = uint64(extra)

	}
	// t.CreateTime (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.CreateTime = uint64(extra)

	}
	// t.PrevSnapShot (string) (string)

	{
		sval, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return err
		}

		t.PrevSnapShot = string(sval)
	}
	// t.ExtraInfo (types.ExtraInfo) (struct)

	{

		b, err := br.ReadByte()
		if err != nil {
			return err
		}
		if b != cbg.CborNull[0] {
			if err := br.UnreadByte(); err != nil {
				return err
			}
			t.ExtraInfo = new(ExtraInfo)
			if err := t.ExtraInfo.UnmarshalCBOR(br); err != nil {
				return xerrors.Errorf("unmarshaling t.ExtraInfo pointer: %w", err)
			}
		}

	}
	return nil
}
