// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.0
// source: pando.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PandoMessage_MessageType int32

const (
	PandoMessage_ERROR_RESPONSE                 PandoMessage_MessageType = 0
	PandoMessage_GET_SNAPSHOT_CID_LIST          PandoMessage_MessageType = 1
	PandoMessage_GET_SNAPSHOT_CID_LIST_RESPONSE PandoMessage_MessageType = 2
	PandoMessage_GET_SNAPSHOT                   PandoMessage_MessageType = 3
	PandoMessage_GET_SNAPSHOT_RESPONSE          PandoMessage_MessageType = 4
	PandoMessage_REGISTER_PROVIDER              PandoMessage_MessageType = 5
	PandoMessage_REGISTER_PROVIDER_RESPONSE     PandoMessage_MessageType = 6
	PandoMessage_GET_PROVIDER_INFO              PandoMessage_MessageType = 7
	PandoMessage_GET_PROVIDER_INFO_RESPONSE     PandoMessage_MessageType = 8
	PandoMessage_GET_PROVIDER_HEAD              PandoMessage_MessageType = 9
	PandoMessage_GET_PROVIDER_HEAD_RESPONSE     PandoMessage_MessageType = 10
	PandoMessage_GET_PANDO_INFO                 PandoMessage_MessageType = 11
	PandoMessage_GET_PANDO_INFO_RESPONSE        PandoMessage_MessageType = 12
)

// Enum value maps for PandoMessage_MessageType.
var (
	PandoMessage_MessageType_name = map[int32]string{
		0:  "ERROR_RESPONSE",
		1:  "GET_SNAPSHOT_CID_LIST",
		2:  "GET_SNAPSHOT_CID_LIST_RESPONSE",
		3:  "GET_SNAPSHOT",
		4:  "GET_SNAPSHOT_RESPONSE",
		5:  "REGISTER_PROVIDER",
		6:  "REGISTER_PROVIDER_RESPONSE",
		7:  "GET_PROVIDER_INFO",
		8:  "GET_PROVIDER_INFO_RESPONSE",
		9:  "GET_PROVIDER_HEAD",
		10: "GET_PROVIDER_HEAD_RESPONSE",
		11: "GET_PANDO_INFO",
		12: "GET_PANDO_INFO_RESPONSE",
	}
	PandoMessage_MessageType_value = map[string]int32{
		"ERROR_RESPONSE":                 0,
		"GET_SNAPSHOT_CID_LIST":          1,
		"GET_SNAPSHOT_CID_LIST_RESPONSE": 2,
		"GET_SNAPSHOT":                   3,
		"GET_SNAPSHOT_RESPONSE":          4,
		"REGISTER_PROVIDER":              5,
		"REGISTER_PROVIDER_RESPONSE":     6,
		"GET_PROVIDER_INFO":              7,
		"GET_PROVIDER_INFO_RESPONSE":     8,
		"GET_PROVIDER_HEAD":              9,
		"GET_PROVIDER_HEAD_RESPONSE":     10,
		"GET_PANDO_INFO":                 11,
		"GET_PANDO_INFO_RESPONSE":        12,
	}
)

func (x PandoMessage_MessageType) Enum() *PandoMessage_MessageType {
	p := new(PandoMessage_MessageType)
	*p = x
	return p
}

func (x PandoMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PandoMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pando_proto_enumTypes[0].Descriptor()
}

func (PandoMessage_MessageType) Type() protoreflect.EnumType {
	return &file_pando_proto_enumTypes[0]
}

func (x PandoMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PandoMessage_MessageType.Descriptor instead.
func (PandoMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_pando_proto_rawDescGZIP(), []int{0, 0}
}

type PandoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// defines what type of message it is.
	Type PandoMessage_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.PandoMessage_MessageType" json:"type,omitempty"`
	// Value for the message
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PandoMessage) Reset() {
	*x = PandoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pando_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PandoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PandoMessage) ProtoMessage() {}

func (x *PandoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pando_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PandoMessage.ProtoReflect.Descriptor instead.
func (*PandoMessage) Descriptor() ([]byte, []int) {
	return file_pando_proto_rawDescGZIP(), []int{0}
}

func (x *PandoMessage) GetType() PandoMessage_MessageType {
	if x != nil {
		return x.Type
	}
	return PandoMessage_ERROR_RESPONSE
}

func (x *PandoMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pando_proto protoreflect.FileDescriptor

var file_pando_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x61, 0x6e, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd, 0x03, 0x0a, 0x0c, 0x50, 0x61, 0x6e, 0x64, 0x6f, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x6e, 0x64,
	0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xe3,
	0x02, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x0e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45,
	0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x47, 0x45, 0x54, 0x5f, 0x53, 0x4e, 0x41, 0x50, 0x53, 0x48,
	0x4f, 0x54, 0x5f, 0x43, 0x49, 0x44, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x01, 0x12, 0x22, 0x0a,
	0x1e, 0x47, 0x45, 0x54, 0x5f, 0x53, 0x4e, 0x41, 0x50, 0x53, 0x48, 0x4f, 0x54, 0x5f, 0x43, 0x49,
	0x44, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10,
	0x02, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x45, 0x54, 0x5f, 0x53, 0x4e, 0x41, 0x50, 0x53, 0x48, 0x4f,
	0x54, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x47, 0x45, 0x54, 0x5f, 0x53, 0x4e, 0x41, 0x50, 0x53,
	0x48, 0x4f, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x04, 0x12, 0x15,
	0x0a, 0x11, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49,
	0x44, 0x45, 0x52, 0x10, 0x05, 0x12, 0x1e, 0x0a, 0x1a, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45,
	0x52, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f,
	0x4e, 0x53, 0x45, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11, 0x47, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x4f,
	0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x07, 0x12, 0x1e, 0x0a, 0x1a,
	0x47, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x49, 0x4e, 0x46,
	0x4f, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x08, 0x12, 0x15, 0x0a, 0x11,
	0x47, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x48, 0x45, 0x41,
	0x44, 0x10, 0x09, 0x12, 0x1e, 0x0a, 0x1a, 0x47, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49,
	0x44, 0x45, 0x52, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53,
	0x45, 0x10, 0x0a, 0x12, 0x12, 0x0a, 0x0e, 0x47, 0x45, 0x54, 0x5f, 0x50, 0x41, 0x4e, 0x44, 0x4f,
	0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x0b, 0x12, 0x1b, 0x0a, 0x17, 0x47, 0x45, 0x54, 0x5f, 0x50,
	0x41, 0x4e, 0x44, 0x4f, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e,
	0x53, 0x45, 0x10, 0x0c, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pando_proto_rawDescOnce sync.Once
	file_pando_proto_rawDescData = file_pando_proto_rawDesc
)

func file_pando_proto_rawDescGZIP() []byte {
	file_pando_proto_rawDescOnce.Do(func() {
		file_pando_proto_rawDescData = protoimpl.X.CompressGZIP(file_pando_proto_rawDescData)
	})
	return file_pando_proto_rawDescData
}

var file_pando_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pando_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pando_proto_goTypes = []interface{}{
	(PandoMessage_MessageType)(0), // 0: proto.PandoMessage.MessageType
	(*PandoMessage)(nil),          // 1: proto.PandoMessage
}
var file_pando_proto_depIdxs = []int32{
	0, // 0: proto.PandoMessage.type:type_name -> proto.PandoMessage.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pando_proto_init() }
func file_pando_proto_init() {
	if File_pando_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pando_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PandoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pando_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pando_proto_goTypes,
		DependencyIndexes: file_pando_proto_depIdxs,
		EnumInfos:         file_pando_proto_enumTypes,
		MessageInfos:      file_pando_proto_msgTypes,
	}.Build()
	File_pando_proto = out.File
	file_pando_proto_rawDesc = nil
	file_pando_proto_goTypes = nil
	file_pando_proto_depIdxs = nil
}
